name: app
description: Valet Buddy
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_riverpod: ^2.4.6
  http: ^1.1.0
  dio: ^5.3.3
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  date_format: ^2.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
